[project]
name = "fast-slide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mario Taddeucci", email = "mariotaddeucci@gmx.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pydantic>=2.12.5",
]

[project.scripts]
fast-slide = "fast_slide:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
